server:
  port: 8001

spring:
  application:
    name: SpringBootMybatisDemo1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      #mysql驱动包
    url: jdbc:mysql://localhost:3306/testtxc?useUnicode=true&characterEncoding=UTF-8&useSSL=false         #数据库名称
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.orange.entity
#  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
